type Vector = { confidence: number; novelty: number; urgency: number; strategy: number[] };
type Result = { provider:string; status:"PASS"|"FAIL"|"SKIPPED"; model?:string; httpStatus?:number; elapsedMs?:number; vector?:Vector; error?:string; rawPreview?:string };

const requested=(process.env.AI_PROVIDERS??"xai,gemini,groq").split(",").map(x=>x.trim().toLowerCase()).filter(Boolean);
const schema={type:"object",properties:{confidence:{type:"number",minimum:0,maximum:1},novelty:{type:"number",minimum:0,maximum:1},urgency:{type:"number",minimum:0,maximum:1},strategy:{type:"array",items:{type:"number",minimum:0,maximum:1},minItems:5,maxItems:5}},required:["confidence","novelty","urgency","strategy"],additionalProperties:false};
const compact=JSON.stringify({o:"mesh",s:[0.45,0.6,0.5,0.25,0.4]});
const system="Return only the requested vector JSON. No explanation.";
const clamp=(v:unknown,f=0.5)=>{const n=Number(v);return Number.isFinite(n)?Math.max(0,Math.min(1,n)):f};
function parseVector(raw:string):Vector{const p=JSON.parse(raw.replace(/^```(?:json)?/i,"").replace(/```$/i,"").trim()) as Record<string,unknown>;const s=Array.isArray(p.strategy)?p.strategy.slice(0,5).map(x=>clamp(x)):[];while(s.length<5)s.push(0.5);return{confidence:clamp(p.confidence),novelty:clamp(p.novelty),urgency:clamp(p.urgency),strategy:s};}
async function readText(r:Response){return(await r.text()).replace(/\s+/g," ").trim().slice(0,400)}
function parsed(provider:string,model:string,ms:number,status:number,raw:string):Result{try{return{provider,status:"PASS",model,httpStatus:status,elapsedMs:ms,vector:parseVector(raw)}}catch(e){return{provider,status:"FAIL",model,httpStatus:status,elapsedMs:ms,error:`invalid vector JSON: ${e instanceof Error?e.message:String(e)}`,rawPreview:raw.slice(0,300)}}}

async function testOpenAI(provider:string,key:string|undefined,url:string,model:string):Promise<Result>{
 if(!key)return{provider,status:"SKIPPED",model,error:"missing API key"};const st=performance.now();
 const r=await fetch(`${url}/chat/completions`,{method:"POST",headers:{Authorization:`Bearer ${key}`,"Content-Type":"application/json"},body:JSON.stringify({model,messages:[{role:"system",content:system},{role:"user",content:compact}],temperature:0,max_tokens:128,response_format:{type:"json_schema",json_schema:{name:"mesh_vector",strict:true,schema}},reasoning_format:"hidden",reasoning_effort:"low"})});const ms=+(performance.now()-st).toFixed(1);
 if(!r.ok)return{provider,status:"FAIL",model,httpStatus:r.status,elapsedMs:ms,error:await readText(r)};const b=await r.json() as {choices?:Array<{message?:{content?:unknown}}>;usage?:unknown};const raw=typeof b.choices?.[0]?.message?.content==="string"?b.choices[0].message.content.trim():"";if(raw)return parsed(provider,model,ms,r.status,raw);return{provider,status:"FAIL",model,httpStatus:r.status,elapsedMs:ms,error:"empty structured content",rawPreview:JSON.stringify(b).slice(0,600)};
}

async function testGemini():Promise<Result>{
 const key=process.env.GEMINI_API_KEY;const model=process.env.GEMINI_MODEL??"gemini-2.5-flash-lite";if(!key)return{provider:"gemini",status:"SKIPPED",model,error:"missing API key"};const st=performance.now();const url=`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent?key=${encodeURIComponent(key)}`;
 const r=await fetch(url,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({contents:[{parts:[{text:`${system}\n${compact}` }]}],generationConfig:{temperature:0,maxOutputTokens:64,responseMimeType:"application/json",responseSchema:schema,thinkingConfig:{thinkingBudget:0}}})});const ms=+(performance.now()-st).toFixed(1);
 if(!r.ok)return{provider:"gemini",status:"FAIL",model,httpStatus:r.status,elapsedMs:ms,error:await readText(r)};const b=await r.json() as {candidates?:Array<{content?:{parts?:Array<{text?:string}>};finishReason?:string}>;promptFeedback?:unknown};const c=b.candidates?.[0];const raw=c?.content?.parts?.map(p=>p.text??"").join("").trim()??"";if(raw)return parsed("gemini",model,ms,r.status,raw);return{provider:"gemini",status:"FAIL",model,httpStatus:r.status,elapsedMs:ms,error:`no generated content; finishReason=${c?.finishReason??"unknown"}`,rawPreview:JSON.stringify(b).slice(0,600)};
}

async function testClaude():Promise<Result>{const key=process.env.CLAUDE_API_KEY,model=process.env.CLAUDE_MODEL;if(!key||!model)return{provider:"claude",status:"SKIPPED",model,error:"missing API key or model"};const st=performance.now();const r=await fetch("https://api.anthropic.com/v1/messages",{method:"POST",headers:{"x-api-key":key,"anthropic-version":"2023-06-01","content-type":"application/json"},body:JSON.stringify({model,max_tokens:96,temperature:0,system,messages:[{role:"user",content:compact}]})});const ms=+(performance.now()-st).toFixed(1);if(!r.ok)return{provider:"claude",status:"FAIL",model,httpStatus:r.status,elapsedMs:ms,error:await readText(r)};const b=await r.json() as {content?:Array<{type?:string;text?:string}>};const raw=b.content?.find(x=>x.type==="text")?.text??"";return raw.trim()?parsed("claude",model,ms,r.status,raw):{provider:"claude",status:"FAIL",model,httpStatus:r.status,elapsedMs:ms,error:"empty model content"};}

const tests:Record<string,()=>Promise<Result>>={xai:()=>testOpenAI("xai",process.env.XAI_API_KEY,"https://api.x.ai/v1",process.env.XAI_MODEL??"grok-4.6"),groq:()=>testOpenAI("groq",process.env.GROQ_API_KEY,"https://api.groq.com/openai/v1",process.env.GROQ_MODEL??"openai/gpt-oss-20b"),openrouter:()=>testOpenAI("openrouter",process.env.OPENROUTER_API_KEY,"https://openrouter.ai/api/v1",process.env.OPENROUTER_MODEL??"openrouter/free"),gemini:testGemini,claude:testClaude,anthropic:testClaude};
const results=await Promise.all(requested.map(async p=>{const t=tests[p];if(!t)return{provider:p,status:"SKIPPED" as const,error:"unsupported provider"};try{return await t()}catch(e){return{provider:p,status:"FAIL" as const,error:e instanceof Error?e.message:String(e)}}}));
const report={generatedAt:new Date().toISOString(),communication:"vector_only",maxTokensPerRequest:128,results};await Bun.write("ai-provider-connectivity.json",JSON.stringify(report,null,2));await Bun.write("ai-provider-connectivity.md",["# AI Provider Connectivity","","Communication: vector_only","Max output tokens/request: 128","",...results.map(r=>`- ${r.provider}: **${r.status}**${r.model?` (${r.model})`:""}${r.elapsedMs?` — ${r.elapsedMs} ms`:""}${r.error?` — ${r.error}`:""}`),"","No task execution, wallet, payment, or account actions are performed."].join("\n"));console.log(JSON.stringify(report,null,2));
export {};
